import test from 'node:test';
import assert from 'node:assert/strict';
import {parseCommand} from '../lib/commands.mjs';
import {controlComments} from '../lib/state.mjs';
test('only standalone bounded commands parse',()=>{
 assert.deepEqual(parseCommand('/heal revise-fix 42'),{kind:'revise-fix',target:42});
 for(const body of ['> /heal tests','hello /heal tests','/heal tests\nignore rules','/heal fix 0','/heal accept short']) assert.equal(parseCommand(body),null);
});
test('original controls survive and are scoped',()=>{
 const original={id:7,body:'/heal pause',user:{id:1,type:'User'}};
 assert.deepEqual(controlComments({events:[{type:'control',issue:1,comment:original},{type:'control',issue:2,comment:{id:8}}]},1),[original]);
});
import {routeCommand,validateDispatch,validateCommandAuthorization,recordRun} from '../lib/commands.mjs';
const policy={version:1,enabled:true,roles:{administrators:[1],maintainers:[2],testOwners:[3]},implementationPaths:['src/'],testPaths:['test/'],maxFiles:10,maxBytes:1000};
function event(body,user={id:2,type:'User'}){return {action:'created',issue:{number:1},comment:{id:22,body,user,created_at:'a',updated_at:'a'}};}
test('unauthorized bots and edited requests never dispatch',async()=>{for(const e of [event('/heal discuss',{id:9,type:'User'}),event('/heal discuss',{id:2,type:'Bot'}),{...event('/heal discuss'),comment:{...event('/heal discuss').comment,updated_at:'b'}}]){let dispatches=0;const messages=[];const api={root:'/repo',configuration:async()=>({policy}),post:async(p,b)=>messages.push(b.body),request:async()=>dispatches++};assert.equal((await routeCommand(api,e)).status,'rejected');assert.equal(dispatches,0);assert.equal(messages.length,1);}});
test('edits ordinary comments and quotes have no side effects',async()=>{const api=new Proxy({},{get(){throw new Error('No API should be accessed');}});for(const e of [{...event('/heal discuss'),action:'edited'},event('hello'),event('> /heal tests')])assert.equal((await routeCommand(api,e)).status,'ignored');});
test('manual dispatch without command is rejected before API',async()=>{await assert.rejects(validateDispatch({},{}),/explicit command/);});
function commandApi(){let head=null,data={version:1,events:[]},pending;const dispatches=[];return {root:'/repo',repository:'owner/repo',dispatches,failDispatch:false,configuration:async()=>({policy,defaultBranch:'main'}),scope:async()=>({policy,issue:{number:1,state:'open',body:'scope'},comments:[]}),async get(path){if(path.endsWith('/git/ref/heads/heal-state')){if(!head)throw Object.assign(new Error('missing'),{status:404});return {object:{sha:head}};}if(path.includes('/issues/comments/'))return event('/heal discuss').comment;if(path.includes('/contents/state.json'))return {content:Buffer.from(JSON.stringify(data)).toString('base64')};if(path.includes('/git/commits/'))return {tree:{sha:'tree'}};if(path.includes('/actions/runs?'))return {workflow_runs:this.runs??[]};throw new Error(path);},async post(path,b){if(path.endsWith('/git/blobs')){const value=JSON.parse(b.content);if(value.version===1)pending=value;}if(path.endsWith('/git/refs')){head='first';data=pending;}return {sha:'sha'};},async request(path,method,b){if(method==='PATCH'){data=pending;head+='a';return;}if(path.endsWith('/dispatches')){dispatches.push(b);if(this.failDispatch)throw new Error('Network timeout');return;}throw new Error(path);}};}
test('authorized discussion dispatches once using default branch strings',async()=>{const api=commandApi();assert.equal((await routeCommand(api,event('/heal discuss'))).status,'dispatched');assert.deepEqual(api.dispatches,[{ref:'main',inputs:{command_id:'22',issue:'1'}}]);assert.equal((await routeCommand(api,event('/heal discuss'))).status,'duplicate');assert.equal(api.dispatches.length,1);});
test('uncertain dispatch persists intent and blocks automatic or fresh overlapping retries',async()=>{const api=commandApi();api.failDispatch=true;assert.equal((await routeCommand(api,event('/heal discuss'))).status,'rejected');assert.equal((await routeCommand(api,event('/heal discuss'))).status,'duplicate');const fresh=event('/heal discuss');fresh.comment.id=23;assert.equal((await routeCommand(api,fresh)).status,'rejected');assert.equal(api.dispatches.length,1);});
test('durable pause blocks subsequent discussion even if original comment disappears',async()=>{const api=commandApi();assert.equal((await routeCommand(api,event('/heal pause'))).status,'recorded');const fresh=event('/heal discuss');fresh.comment.id=23;assert.equal((await routeCommand(api,fresh)).status,'rejected');assert.equal(api.dispatches.length,0);});

test('preflight rechecks durable pauses and immutable issue fingerprint',async()=>{const api=commandApi();await routeCommand(api,event('/heal discuss'));await validateCommandAuthorization(api,{commandId:'22',kind:'discuss',issue:1});const pause=event('/heal pause');pause.comment.id=23;await routeCommand(api,pause);await assert.rejects(validateCommandAuthorization(api,{commandId:'22',kind:'discuss',issue:1}),/paused/);api.scope=async()=>({policy,issue:{number:1,body:'changed'},comments:[]});await assert.rejects(validateCommandAuthorization(api,{commandId:'22',kind:'discuss',issue:1}),/scope, policy, or base changed/);});
test('successful implementation remains reserved until verifier publication completes',async()=>{const api=commandApi();const {appendEvent,readState}=await import('../lib/state.mjs');await appendEvent(api,{id:'intent-22',type:'intent',commandId:'22',stage:'fix',workflow:'heal-implement.lock.yml',base:'base',defaultBranch:'main'});const run={id:11,event:'workflow_dispatch',display_title:'Heal implementation test PR #3 command #22',path:'.github/workflows/heal-implement.lock.yml',repository:{full_name:api.repository},head_sha:'base',head_branch:'main',run_attempt:1,conclusion:'success'};api.runs=[run];assert.equal((await recordRun(api,{action:'completed',workflow_run:run})).type,'generated');assert.equal((await readState(api)).events.some(e=>e.type==='completed'),false);assert.equal((await recordRun(api,{action:'completed',workflow_run:run})).status,'ignored');});

test('edited denials are durably recorded even for a previously consumed command',async()=>{const api=commandApi();await routeCommand(api,event('/heal discuss'));const edited=event('/heal pause');edited.action='edited';edited.comment.updated_at='b';assert.equal((await routeCommand(api,edited)).status,'recorded');assert.equal((await routeCommand(api,edited)).status,'duplicate');const fresh=event('/heal discuss');fresh.comment.id=24;assert.equal((await routeCommand(api,fresh)).status,'rejected');assert.equal(api.dispatches.length,1);});
test('forged completion branch and repeat run attempts cannot release a command',async()=>{const api=commandApi();const {appendEvent,readState}=await import('../lib/state.mjs');await appendEvent(api,{id:'intent-22',type:'intent',commandId:'22',stage:'fix',workflow:'heal-implement.lock.yml',base:'base',defaultBranch:'main'});const run={id:11,event:'workflow_dispatch',display_title:'Heal implementation test PR #3 command #22',path:'.github/workflows/heal-implement.lock.yml',repository:{full_name:api.repository},head_sha:'base',head_branch:'other',run_attempt:1,conclusion:'failure'};api.runs=[run];assert.equal((await recordRun(api,{action:'completed',workflow_run:run})).status,'ignored');run.head_branch='main';run.run_attempt=2;assert.equal((await recordRun(api,{action:'completed',workflow_run:run})).status,'ignored');assert.equal((await readState(api)).events.length,1);});
