import test from 'node:test';
import assert from 'node:assert/strict';
import {readState,appendEvent} from '../lib/state.mjs';
function fake(){let head=null,n=0;const blobs={},trees={},commits={};return {root:'/repo',get head(){return head},envelope(){return JSON.parse(blobs[trees[commits[head].tree].find(x=>x.path==='state.json').sha]);},alter(fn){const blob=trees[commits[head].tree].find(x=>x.path==='state.json').sha;blobs[blob]=JSON.stringify(fn(JSON.parse(blobs[blob])));},race:false,async get(path){if(path.endsWith('/git/ref/heads/heal-state')){if(!head)throw Object.assign(new Error('missing'),{status:404});return {object:{sha:head}};}if(path.includes('/contents/state.json'))return {content:Buffer.from(blobs[trees[commits[head].tree].find(x=>x.path==='state.json').sha]).toString('base64')};if(path.includes('/git/commits/'))return {tree:{sha:commits[head].tree},parents:commits[head].parents.map(sha=>({sha}))};throw new Error(path);},async post(path,b){const sha=String(++n);if(path.endsWith('/git/blobs'))blobs[sha]=b.content;else if(path.endsWith('/git/trees'))trees[sha]=b.tree;else if(path.endsWith('/git/commits'))commits[sha]=b;else if(path.endsWith('/git/refs')){if(head)throw new Error('race');head=b.sha;}return {sha};},async request(path,method,b){assert.equal(method,'PATCH');assert.equal(b.force,false);if(this.race)throw new Error('non fast forward');assert.equal(commits[b.sha].parents[0],head);head=b.sha;}};}
test('state appends immutable events and never forces refs',async()=>{const api=fake();assert.deepEqual(await readState(api),{head:null,events:[]});const first=await appendEvent(api,{id:'a',type:'control',issue:1},{expectedHead:null});await appendEvent(api,{id:'b',type:'intent'},{expectedHead:first.head});assert.deepEqual((await readState(api)).events.map(x=>x.id),['a','b']);await assert.rejects(appendEvent(api,{id:'c'},{expectedHead:first.head}),/state changed/);await assert.rejects(appendEvent(api,{id:'a'}),/Duplicate/);});
test('CAS conflict fails closed and retains original history',async()=>{const api=fake();await appendEvent(api,{id:'a'});api.race=true;await assert.rejects(appendEvent(api,{id:'b'}),/non fast forward/);assert.deepEqual((await readState(api)).events,[{id:'a'}]);});
import {generateKeyPairSync,sign} from 'node:crypto';
const keys=generateKeyPairSync('ed25519');
const publicPem=keys.publicKey.export({type:'spki',format:'pem'});
const privatePem=keys.privateKey.export({type:'pkcs8',format:'pem'});
function signedFake(){const api=fake();api.enforceStateSignature=true;api.configuration=async()=>({policy:{statePublicKey:publicPem}});return api;}
async function withSigningKey(key,action){const previous=process.env.HEAL_STATE_PRIVATE_KEY;process.env.HEAL_STATE_PRIVATE_KEY=key;try{return await action();}finally{if(previous===undefined)delete process.env.HEAL_STATE_PRIVATE_KEY;else process.env.HEAL_STATE_PRIVATE_KEY=previous;}}
test('production signed append round trips and binds each parent',async()=>{await withSigningKey(privatePem,async()=>{const api=signedFake();const first=await appendEvent(api,{id:'a'});await appendEvent(api,{id:'b'});assert.equal(api.envelope().parent,first.head);assert.equal(typeof api.envelope().signature,'string');assert.deepEqual((await readState(api)).events,[{id:'a'},{id:'b'}]);});});
test('production refuses unsigned state or tampered event history',async()=>{const api=signedFake();api.enforceStateSignature=false;await appendEvent(api,{id:'a'});api.enforceStateSignature=true;await assert.rejects(readState(api),/signature/);await withSigningKey(privatePem,async()=>{const signed=signedFake();await appendEvent(signed,{id:'a'});signed.alter(x=>{x.events.push({id:'forged'});return x;});await assert.rejects(readState(signed),/signature/);});});
test('production refuses missing public key and wrong signing key before writes',async()=>{const api=signedFake();api.configuration=async()=>({policy:{}});await assert.rejects(readState(api),/public key/);const other=generateKeyPairSync('ed25519').privateKey.export({type:'pkcs8',format:'pem'});await withSigningKey(other,async()=>{const wrong=signedFake();await assert.rejects(appendEvent(wrong,{id:'a'}),/signature|signing key/);assert.equal(wrong.head,null);});});
test('copying an older signed envelope onto a descendant fails parent binding',async()=>{await withSigningKey(privatePem,async()=>{const api=signedFake();await appendEvent(api,{id:'a'});const original=api.envelope();await appendEvent(api,{id:'b'});api.alter(()=>original);await assert.rejects(readState(api),/parent/);});});
test('production rejects signatures made by a different authority',async()=>{await withSigningKey(privatePem,async()=>{const api=signedFake();await appendEvent(api,{id:'a'});const attacker=generateKeyPairSync('ed25519').privateKey;api.alter(x=>({...x,signature:sign(null,Buffer.from(JSON.stringify({version:x.version,events:x.events,parent:x.parent})),attacker).toString('base64')}));await assert.rejects(readState(api),/signature/);});});

